'''
This file contains the node colors for the graph viewer.
'''

node_colors = \
{
    "root": "red",
    "transform": "SteelBlue",
    "room": "Gray",
    "differentialrobot": "GoldenRod",
    "omnirobot": "GoldenRod",
    "robot": "Gray",
    "path_to_target": "Gray",
    "intention": "Gray",
    "rgbd": "Gray",
    "pan_tilt": "Gray",
    "battery": "Gray",
    "pose": "Gray",
    "laser": "GreenYellow",
    "camera": "Gray",
    "imu": "LightSalmon",
    "slam_device": "Gray",
    "object": "Gray",
    "affordance_space": "Gray",
    "person": "Gray",
    "personal_space": "Gray",
    "plane": "Khaki",
    "box": "Gray",
    "cylinder": "Gray",
    "ball": "Gray",
    "mesh": "LightBlue",
    "face": "Gray",
    "body": "Gray",
    "chest": "Gray",
    "nose": "Gray",
    "left_eye": "Gray",
    "right_eye": "Gray",
    "left_ear": "Gray",
    "right_ear": "Gray",
    "left_arm": "Gray",
    "right_arm": "Gray",
    "left_shoulder": "Gray",
    "right_shoulder": "Gray",
    "left_elbow": "Gray",
    "right_elbow": "Gray",
    "left_wrist": "Gray",
    "right_wrist": "Gray",
    "left_hand": "Gray",
    "right_hand": "Gray",
    "left_hip": "Gray",
    "right_hip": "Gray",
    "left_leg": "Gray",
    "right_leg": "Gray",
    "left_knee": "Gray",
    "right_knee": "Gray",
    "mug": "Gray",
    "cup": "Gray",
    "noodles": "Gray",
    "table": "Gray",
    "chair": "Gray",
    "shelve": "Gray",
    "dish": "Gray",
    "spoon": "Gray",
    "testtype": "Gray",
    "glass": "Gray",
    "plant": "Gray",
    "microwave": "Gray",
    "oven": "Gray",
    "vase": "Gray",
    "refrigerator": "Gray",
    "road": "Gray",
    "building": "Gray",
    "vehicle": "Gray",
    "gps": "Gray",
    "grid": "Gray",
    "agent": "Gray"
}
