
[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"

# Proxies for publishes interfaces
CameraRGBDSimplePubPrefix = ""
FullPoseEstimationPubPrefix = ""
IMUPubPrefix = ""

# Proxies for required interfaces
CameraRGBDSimple = "camerargbdsimple:tcp -h localhost -p 0"






[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
