#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
#    Copyright (C) 2024 by YOUR NAME HERE
#
#    This file is part of RoboComp
#
#    RoboComp is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    RoboComp is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with RoboComp.  If not, see <http://www.gnu.org/licenses/>.
#
import numpy as np
from PySide2.QtCore import QTimer
from PySide2.QtWidgets import QApplication
from rich.console import Console
from genericworker import *
import interfaces as ifaces

sys.path.append('/opt/robocomp/lib')
console = Console(highlight=False)

from pydsr import *

class SpecificWorker(GenericWorker):
    def __init__(self, proxy_map, startup_check=False):
        """
        Sets up the DSRGraph object and connects it to signal for updates on nodes
        and edges, start a timer with a period of 100, and handles errors. It also
        initializes variables for current room, state, affordance node active ID,
        room exit door ID, enter room node ID, and exit door ID.

        Args:
            proxy_map (object.): 2D or 3D spatial map that the agent operates
                within and serves as the graph for the DSRGraph instance created
                and connected to the Super class's methods, allowing the agent to
                navigate and interact with its environment.
                
                		- `proxy_map`: A map containing proxy information for the graph.
                
                	Explanation of each property in `proxy_map`:
                
                		- `agent_id`: An unique integer identifier assigned to this agent
                in deployment.
                		- `Period`: The interval between updates (in milliseconds).
                
                	No further explanation is provided as it is a plain map with two
                key-value pairs.
            startup_check (`object` (possibly subclass of `Exception`)): whether
                to run the `startup_check()` method during initialization, which
                checks if the graph has a room node and ensures that the current
                edge is set to the first edge connected to it.
                
                	1/ `startup_check`: This is a boolean attribute that indicates
                whether the check for starting the agent was successful or not.
                It is set to `True` if the check is successful and `False` otherwise.
                	2/ `runtimeError`: This is an error message generated by connecting
                signals, indicating that there is an issue with the connection.
                It is set to a `RuntimeError` object in case of any error.

        """
        super(SpecificWorker, self).__init__(proxy_map)
        self.Period = 100

        # YOU MUST SET AN UNIQUE ID FOR THIS AGENT IN YOUR DEPLOYMENT. "_CHANGE_THIS_ID_" for a valid unique integer
        self.agent_id = 13
        self.g = DSRGraph(0, "LongTermSpatialMemory_agent", self.agent_id)

        try:
            #signals.connect(self.g, signals.UPDATE_NODE_ATTR, self.update_node_att)
            signals.connect(self.g, signals.UPDATE_NODE, self.update_node)
            #signals.connect(self.g, signals.DELETE_NODE, self.delete_node)
            signals.connect(self.g, signals.UPDATE_EDGE, self.update_edge)
            #signals.connect(self.g, signals.UPDATE_EDGE_ATTR, self.update_edge_att)
            #signals.connect(self.g, signals.DELETE_EDGE, self.delete_edge)
            console.print("signals connected")
        except RuntimeError as e:
            print(e)

        if startup_check:
            self.startup_check()
        else:
            self.rt_api = rt_api(self.g)
            self.inner_api = inner_api(self.g)
            self.room_initialized = False

            # self.states = ["idle", "crossing", "crossed", "initializing_room", "new_room", "initializing_doors", "removing"]
            self.state = "idle"
            self.affordance_node_active_id = None
            self.room_exit_door_id = None
            self.enter_room_node_id = None
            self.exit_door_id = None

            # Check if there is a current room node in the graph
            room_nodes = self.g.get_nodes_by_type("room")
            current_room_nodes = [node for node in room_nodes if self.g.get_edge(node.id, node.id, "current")]
            if len(current_room_nodes) == 0 and len(room_nodes) == 1:
                print("Room node exists but no current edge. Setting as current")
                if not "measured" in room_nodes[0].name:
                    self.insert_current_edge(room_nodes[0].id)


            self.timer.timeout.connect(self.compute)
            self.timer.start(self.Period)

    def __del__(self):
        """Destructor"""

    def setParams(self, params):
        """
        Checks if a node of type "aff_cross" has its valid attribute set to true,
        then determines if an exit door can be found and removed from a room based
        on various conditions related to the robot's pose and the presence of a
        valid other side door.

        Args:
            params (object.): 4-element list containing the ID of the node to
                check, the room ID, the node's status, and the robot's pose.
                
                	1/ `type`: The parameter `type` specifies the type of operation
                to be performed. It can take one of the following values: `'cross'`,
                `'enter'`, or `'exit'`.
                	2/ `room`: This attribute holds the ID of the current room that
                the algorithm is working on.
                	3/ `node`: This attribute represents the current node in the
                graph, which is either an aff_cross, enter, or exit node.
                	4/ `valid`: This attribute indicates whether the node is valid
                or not. If it is `True`, then the node is considered valid and
                further processing is carried out. If it is `False`, then the
                algorithm exits with a suitable error message.
                	5/ `completed`: This attribute specifies whether the operation
                has been completed successfully or not. If it is `True`, then the
                operation was successful, otherwise, it failed.
                	6/ `was_active`: This attribute indicates whether the operation
                was active at any point in time during its execution. If it is
                `True`, then the operation was active; otherwise, it was not.
                	7/ `robot_pose`: This attribute holds the position of the robot
                relative to the current room.
                	8/ `other_side_door`: This attribute represents the name of the
                other side door in case an enter or exit operation is performed.
                
                	The function proceeds based on the value of `type`, processing
                accordingly for each type of operation.

        Returns:
            bool: a boolean value indicating whether the node was updated successfully.

        """
        return True

        # PROTOcode
        # Check if there is a node of type aff_cross and it has it's valid attribute to true
        # if so, check if aff_cross status attribute is completed, was active and robot pose is outside the room polygon,

        # - then remove "current" self-edge from the room
        # - Store in a variable the ID of the exit door
        # - wait until a new room is stabilized
        # - when new room is stabilized, check for the door used to get inside
        # - store in both doors the other_side_door name attribute
        # - Read exit door node and add an attribute other_side_door with the name of the entrance door in the new room
        # - Read entrance door node and add an attribute other_side_door with the name of the exit door in the new room
    @QtCore.Slot()
    def compute(self):
        """
        Is a state machine that manages the different states an agent can be in,
        based on its current state and the given action. It transitions the agent
        to the appropriate next state according to the function's predefined logic.

        """
        match self.state:
            case "idle":
                self.idle()
            case "crossing":
                self.crossing()
            case "crossed":
                self.crossed()
            case "initializing_room":
                self.initializing_room()
            case "new_room":
                self.new_room()
            case "initializing_doors":
                self.initializing_doors()
            case "removing":
                self.removing()

    def idle(self):
        """
        1) checks for aff_cross nodes with valid active attribute and 2) determines
        the room exit door id and affordance node active id based on current edges
        and sets the state to "crossing" if possible.

        """
        print("IDLE")
        # Check if there is a node of type aff_cross and it has it's valid attribute to true using comprehension list
        aff_cross_nodes = [node for node in self.g.get_nodes_by_type("aff_cross") if node.attrs["active"] == "true"]
        # Check if not empty
        if len(aff_cross_nodes) == 0 or len(aff_cross_nodes) > 1:
            print("No aff_cross nodes with valid attribute or more than one valid affordance")
            return
        else:
            current_edges = [edge for edge in self.g.get_edges_by_type("current") if self.g.get_node(edge.to).type == "room" and self.g.get_node(edge.fr).type == "room"]
            if len(current_edges) == 1:
                self.room_exit_door_id = current_edges[0].fr
                self.affordance_node_active_id = aff_cross_nodes[0].id
                self.state = "crossing"
            else:
                print("No current room")
                return

    def crossing(self):
        """
        Determines if an affordance node has a "completed" status and is not
        currently active, then it directs the agent to the "crossed" state.

        """
        print("CROSSING")
        # Check if affordance_node has status attribute completed and is not active
        affordance_node = self.g.get_node(self.affordance_node_active_id)
        if affordance_node.attrs["status"] == "completed" and affordance_node.attrs["active"] == "false":
            print("Affordance node is completed and not active. Go to crossed state")
            self.state = "crossed"

    def crossed(self):
        """
        Retrieves the parent node of an active affordance node and sets the exit
        door ID to its value if it exists. It also removes a self-edge from the
        room graph marked "current".

        """
        print("CROSSED")
        # Get parent node of affordance node
        affordance_node = self.g.get_node(self.affordance_node_active_id)
        if not affordance_node.attrs["parent"].value:
            print("Affordance node has no parent")
            return
        else:
            self.exit_door_id = affordance_node.attrs["parent"].value
            # Remove "current" self-edge from the room
            self.g.delete_edge(self.room_exit_door_id, self.room_exit_door_id, "current")
            self.state = "initializing_room"

    def initializing_room(self):
        """
        Gets a list of room nodes from the graph, checks if there are any room
        nodes different from the exit door node, and sets the enter room node ID
        to the first non-exit room node found.

        """
        print("INITIALIZING ROOM")
        # Get room nodes
        room_nodes = [node for node in self.g.get_nodes_by_type("room") if node.id != self.room_exit_door_id]
        if len(room_nodes) == 0:
            print("No room nodes different from the exit one found")
            return
        else:
            # Get the enter room node id
            self.enter_room_node_id = room_nodes[0].id
            self.state = "initializing_doors"
    #
    # def new_room(self):
    #     pass

    def initializing_doors(self):
        """
        1) checks if a room entry node exists and has type "room", 2) finds all
        same edges leading to the door entry node, 3) retrieves the other side
        door ID, and 4) adds attributes to both exit and enter doors to reference
        each other.

        """
        print("INITIALIZING DOORS")
        # Check if node called "room_entry" of type room exists
        door_entry_node = self.g.get_node("door_entry")
        if door_entry_node and door_entry_node.type == "door":
            # Check if edge of type "same" exists between door_entry and enter_room_node
            same_edges = self.g.get_edges_by_type("same")
            if len(same_edges) == 0:
                print("No same edges found")
                return
            else:
                # Get the other side door id TODO: the edge comes from door_entry to nominal door (set in door_detector)
                other_side_door_id = same_edges[0].to
                # Read exit door node and add an attribute other_side_door with the name of the entrance door in the new room
                exit_door_node = self.g.get_node(self.exit_door_id)
                exit_door_node.attrs["other_side_door"] = other_side_door_id
                # Read entrance door node and add an attribute other_side_door with the name of the exit door in the new room
                enter_door_node = self.g.get_node(self.enter_room_node_id)
                enter_door_node.attrs["other_side_door"] = self.exit_door_id
                self.g.update_node(exit_door_node)
                self.g.update_node(enter_door_node)
                self.state = "removing"

    def removing(self):
        """
        Determines whether the current room is still valid and if not, creates a
        proxy empty room node with the doors as children nodes, saving the old
        room and gist in the agent's internal graph. It also checks for any active
        goto edges connecting the robot and a door and removes the self-edge when
        necessary.

        """
        pass




        # # check it there is an active goto edge connecting the robot and a door
        #     # if so, then check the robot position. If it is at the door
        #         # signal that the current room is not anymore by removing self-edge
        #         # wait for a new room to be created
        #         # when new room is created, check for the first door in it.  Should be the door used to get in
        #         # connect both doors with a new edge "same"
        #         ### loop-closure  PARA LA SEGUNDA VUELTA  (gist es una imagen 360 de la habitación usada para reconocerla rápidamente)
        #         # check if the current room "gist" is similar to the gists of the other rooms in the agent's internal graph.
        #         # if so, then replace the current room by the matching nominal room in the internal graph
        #             # and adjust door connections
        # # if not, then check if there is a room not marked as "current" that has been there for at least 1 minute
        #     # if so, then replace the not-current room by a proxy empty room node with the doors as children nodes
        #         # save the old room in the agent's internal graph
        #         # save a gist of the room in the agent's internal graph
        #         # connect the door connecting both rooms with a new edge "same"
        #
        # # check it there is an active goto edge connecting the robot and a door
        # goto_edges = self.g.get_edges_by_type("goto")
        # if len(goto_edges) > 0:
        #     # search if one of the edges in goto_edges goes to a door
        #     for edge in goto_edges:
        #         if edge.fr.name == "robot" and edge.to.name == "door":
        #             # get door coordinates transformed to robot coordinates are smaller than 100mm
        #             door_coords_in_robot = self.inner_api(edge.fr.name, edge.to.name)
        #             # check that door_coords_in_robot are smaller than 100mm
        #             if np.sqrt(np.power(door_coords_in_robot[0], 2) + np.power(door_coords_in_robot[1], 2)) < 100:
        #                 # signal that the current room is not anymore by removing self-edge
        #                 self.g.remove_edge(edge.fr.name, edge.to.name, "current")
        #                 # wait for a new room to be created

    def insert_current_edge(self, room_id):
        # Insert current edge to the room
        current_edge = Edge(room_id, room_id, "current", self.agent_id)
        self.g.insert_or_assign_edge(current_edge)

    def startup_check(self):
        QTimer.singleShot(200, QApplication.instance().quit)

    # =============== DSR SLOTS  ================
    # =============================================

    def update_node_att(self, id: int, attribute_names: [str]):
        console.print(f"UPDATE NODE ATT: {id} {attribute_names}", style='green')

    def update_node(self, id: int, type: str):
        # Insert current edge to the room
        """
        Updates the current edge of a room node in a graph based on its existence
        and type, without any measured edges.

        Args:
            id (int): unique identifier of the node for which the current edge
                will be set.
            type (str): type of node to search for, which in this case is "room".

        """
        if len(self.g.get_nodes_by_type("room")) == 1 and type == "room" and not "measured" in self.g.get_node(id).name:
            print("Room node exists but no current edge. Setting as current")
            self.insert_current_edge(id)

    def delete_node(self, id: int):
        console.print(f"DELETE NODE:: {id} ", style='green')

    def update_edge(self, fr: int, to: int, type: str):
        pass
        # console.print(f"UPDATE EDGE: {fr} to {type}", type, style='green')

    def update_edge_att(self, fr: int, to: int, type: str, attribute_names: [str]):
        console.print(f"UPDATE EDGE ATT: {fr} to {type} {attribute_names}", style='green')

    def delete_edge(self, fr: int, to: int, type: str):
        console.print(f"DELETE EDGE: {fr} to {type} {type}", style='green')
