
[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"



[Endpoints]
# Endpoints for subscriptions interfaces
FullPoseEstimationPubTopic = "tcp -p 0"



[Agent]
id = 0 # Change id
name = "shadow_agent"
configFile = ""

[ViewAgent]
tree = true
graph = true
2d = true
3d = true

[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
