//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `Person.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Person.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompPerson_Person_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPerson::Person"
};
const ::std::string iceC_RoboCompPerson_Person_ops[] =
{
    "getJointData",
    "getPerson",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setPerson"
};
const ::std::string iceC_RoboCompPerson_Person_getJointData_name = "getJointData";
const ::std::string iceC_RoboCompPerson_Person_getPerson_name = "getPerson";
const ::std::string iceC_RoboCompPerson_Person_setPerson_name = "setPerson";

}

bool
RoboCompPerson::Person::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompPerson_Person_ids, iceC_RoboCompPerson_Person_ids + 2, s);
}

::std::vector<::std::string>
RoboCompPerson::Person::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompPerson_Person_ids[0], &iceC_RoboCompPerson_Person_ids[2]);
}

::std::string
RoboCompPerson::Person::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompPerson::Person::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompPerson::Person";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceD_getJointData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TJointData ret = this->getJointData(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceD_getPerson(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_id;
    istr->readAll(iceP_id);
    inS.endReadParams();
    TPerson ret = this->getPerson(iceP_id, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceD_setPerson(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    TPerson iceP_person;
    istr->readAll(iceP_person);
    inS.endReadParams();
    this->setPerson(::std::move(iceP_person), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompPerson_Person_ops, iceC_RoboCompPerson_Person_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompPerson_Person_ops)
    {
        case 0:
        {
            return _iceD_getJointData(in, current);
        }
        case 1:
        {
            return _iceD_getPerson(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_setPerson(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompPerson::PersonPrx::_iceI_getJointData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompPerson::TJointData>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompPerson_Person_getJointData_name);
    outAsync->invoke(iceC_RoboCompPerson_Person_getJointData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompPerson::PersonPrx::_iceI_getPerson(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompPerson::TPerson>>& outAsync, int iceP_id, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompPerson_Person_getPerson_name);
    outAsync->invoke(iceC_RoboCompPerson_Person_getPerson_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_id);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompPerson::PersonPrx::_iceI_setPerson(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const TPerson& iceP_person, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompPerson_Person_setPerson_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_person);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompPerson::PersonPrx::_newInstance() const
{
    return ::IceInternal::createProxy<PersonPrx>();
}
/// \endcond

const ::std::string&
RoboCompPerson::PersonPrx::ice_staticId()
{
    return Person::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompPerson_Person_getJointData_name = "getJointData";

const ::std::string iceC_RoboCompPerson_Person_getPerson_name = "getPerson";

const ::std::string iceC_RoboCompPerson_Person_setPerson_name = "setPerson";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompPerson::upCast(Person* p) { return p; }

void
::IceProxy::RoboCompPerson::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Person>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Person;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompPerson::Person::_iceI_begin_getJointData(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompPerson_Person_getJointData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompPerson_Person_getJointData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompPerson_Person_getJointData_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompPerson_Person_getJointData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompPerson::TJointData
IceProxy::RoboCompPerson::Person::end_getJointData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompPerson_Person_getJointData_name);
    ::RoboCompPerson::TJointData ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompPerson::Person::_iceI_begin_getPerson(::Ice::Int iceP_id, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompPerson_Person_getPerson_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompPerson_Person_getPerson_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompPerson_Person_getPerson_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_id);
        result->endWriteParams();
        result->invoke(iceC_RoboCompPerson_Person_getPerson_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompPerson::TPerson
IceProxy::RoboCompPerson::Person::end_getPerson(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompPerson_Person_getPerson_name);
    ::RoboCompPerson::TPerson ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompPerson::Person::_iceI_begin_setPerson(const ::RoboCompPerson::TPerson& iceP_person, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompPerson_Person_setPerson_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompPerson_Person_setPerson_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_person);
        result->endWriteParams();
        result->invoke(iceC_RoboCompPerson_Person_setPerson_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompPerson::Person::end_setPerson(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompPerson_Person_setPerson_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompPerson::Person::_newInstance() const
{
    return new Person;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompPerson::Person::ice_staticId()
{
    return ::RoboCompPerson::Person::ice_staticId();
}

RoboCompPerson::Person::~Person()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompPerson::upCast(Person* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompPerson_Person_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPerson::Person"
};

}

bool
RoboCompPerson::Person::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompPerson_Person_ids, iceC_RoboCompPerson_Person_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompPerson::Person::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompPerson_Person_ids[0], &iceC_RoboCompPerson_Person_ids[2]);
}

const ::std::string&
RoboCompPerson::Person::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompPerson::Person::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompPerson::Person";
    return typeId;
#else
    return iceC_RoboCompPerson_Person_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceD_getJointData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TJointData ret = this->getJointData(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceD_getPerson(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_id;
    istr->read(iceP_id);
    inS.endReadParams();
    TPerson ret = this->getPerson(iceP_id, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceD_setPerson(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    TPerson iceP_person;
    istr->read(iceP_person);
    inS.endReadParams();
    this->setPerson(iceP_person, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompPerson_Person_all[] =
{
    "getJointData",
    "getPerson",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setPerson"
};

}

/// \cond INTERNAL
bool
RoboCompPerson::Person::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompPerson_Person_all, iceC_RoboCompPerson_Person_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompPerson_Person_all)
    {
        case 0:
        {
            return _iceD_getJointData(in, current);
        }
        case 1:
        {
            return _iceD_getPerson(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_setPerson(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompPerson::Person::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Person, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompPerson::Person::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Person, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompPerson::_icePatchObjectPtr(PersonPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = PersonPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Person::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
