[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"



[Endpoints]
# Endpoints for subscriptions interfaces
VisualElementsPubTopic = "tcp -p 0"
VisualElementsPubPrefix = ""



[Agent]
id = 0 # Change id
name = "person_detector"
configFile = ""


[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
