[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"


# Proxies for required interfaces
G2Ooptimizer = "g2ooptimizer:tcp -h localhost -p 0"
Lidar3D = "lidar3d:tcp -h localhost -p 0"

[Endpoints]
# Endpoints for subscriptions interfaces
Lidar3DPubTopic = "tcp -p 0"
Lidar3DPubPrefix = ""



[Agent]
id = 0 # Change id
name = "door_detector"
configFile = ""

[ViewAgent]
tree = true
graph = true
2d = true
3d = true

[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
